development: &default

  # Credentials for REST APIs
  client_id: Aaza957jtbOXx1WYMOnLicLrC2ZsjgHpfSNDUiTFoS6cW0AlgjfWSiO-ZR51t8l8fzsg1SVlFQlEiap5
  client_secret: ECgsyLc2TXXFPNf2QiZgjsPYwpEfx1dzNra9NWoS0fESUDCAEEC7uew2fGOeU2DcP2rXvxz4isUhGT-c

  # Mode can be 'live' or 'sandbox'
  mode: sandbox

  # Credentials for Classic APIs
  # app_id: APP-80W284485P519543T
  # username: jb-us-seller_api1.paypal.com
  # password: WX4WTU3S8MY44S7F
  # signature: AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy
  # # With Certificate
  # cert_path: "config/cert_key.pem"
  # sandbox_email_address: Platform.sdk.seller@gmail.com

  # # IP Address
  # ip_address: 127.0.0.1
  # # HTTP Proxy
  # http_proxy: http://proxy-ipaddress:3129/

test:
  <<: *default

production:
  <<: *default
  mode: live
